//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OASUEntities : DbContext
    {
        public OASUEntities()
            : base("name=OASUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computer> Computers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<Document_types> Document_types { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Prg_Systems> Prg_Systems { get; set; }
        public virtual DbSet<PrgLang> PrgLangs { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Records_history> Records_history { get; set; }
        public virtual DbSet<Sub_Systems> Sub_Systems { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Workplace> Workplaces { get; set; }
    }
}
