//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public Nullable<int> Employee_ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> PS_ID { get; set; }
        public Nullable<int> Office_ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<int> Prog_Lang_ID { get; set; }
        public Nullable<int> Profession_ID { get; set; }
        public Nullable<int> Sub_System_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Prg_Systems Prg_Systems { get; set; }
    }
}
